In [29]:
##ЗАДАНИЕ 1.1

In [56]:
import numpy as np
from numpy import linalg as la

N = 12
ALPHA = (N - 50) / 100

In [57]:
A = np.array([
    [50 * (1 + 0.5 * N + ALPHA), 50 * (1 + 0.5 * N), 50 * (1 + 0.5 * N)],
    [50.1 * (1 + 0.5 * N), 49.9 * (1 + 0.5 * N + ALPHA), 50 * (1 + 0.5 * N)],
    [49.9 * (1 + 0.5 * N), 50 * (1 + 0.5 * N), 50.1 * (1 + 0.5 * N + ALPHA)]
])
A_RP = np.array([50 * (3 + 1.5 * N + ALPHA), 50 * (3 + 1.5 * N + ALPHA), 50 * (3 + 1.5 * N + ALPHA)])

In [83]:
print("Матрица СЛАУ\n", A, "\nПравая часть", A_RP)

Матрица СЛАУ
 [[331.    350.    350.   ]
 [350.7   330.338 350.   ]
 [349.3   350.    331.662]] 
Правая часть [1031. 1031. 1031.]


In [63]:
A_inv = la.inv(A)

In [64]:
print("Обратная матрица к А\n", A_inv)

Обратная матрица к А
 [[-0.03480949  0.01726642  0.01851305]
 [ 0.01598276 -0.03355974  0.01854883]
 [ 0.01979422  0.01723064 -0.03605689]]


In [65]:
A_abs = np.absolute(A)
A_inv_abs = np.absolute(A_inv)

In [66]:
print("Модуль элементов A\n", A_abs, "\n\n", "Модуль элементов обратной к А\n", A_inv_abs)

Модуль элементов A
 [[331.    350.    350.   ]
 [350.7   330.338 350.   ]
 [349.3   350.    331.662]] 

 Модуль элементов обратной к А
 [[0.03480949 0.01726642 0.01851305]
 [0.01598276 0.03355974 0.01854883]
 [0.01979422 0.01723064 0.03605689]]


In [81]:
A_norm = la.norm(A, np.inf)
A_inv_norm = la.norm(A_inv, np.inf) 
cond_A = A_norm * A_inv_norm
check_cond_A = la.cond(A, np.inf)

In [82]:
print("Норма А = ", A_norm, "\nНорма обратной матрицы к А = ", A_inv_norm)
print("Число обусловленности A = ", cond_A, "\nПроверка = ", check_cond_A)

Норма А =  1031.038 
Норма обратной матрицы к А =  0.07308174029418962
Число обусловленности A =  75.35005134944068 
Проверка =  75.35005134944068
