In [2]:
##ЗАДАНИЕ 1.1

In [60]:
import numpy as np
from numpy import linalg as la

N = 12
n = 52
ALPHA = (n - 50) / 100

In [61]:
A = np.array([
    [50 * (1 + 0.5 * N + ALPHA), 50 * (1 + 0.5 * N), 50 * (1 + 0.5 * N)],
    [50.1 * (1 + 0.5 * N), 49.9 * (1 + 0.5 * N + ALPHA), 50 * (1 + 0.5 * N)],
    [49.9 * (1 + 0.5 * N), 50 * (1 + 0.5 * N), 50.1 * (1 + 0.5 * N + ALPHA)]
])
b = np.array([50 * (3 + 1.5 * N + ALPHA), 50 * (3 + 1.5 * N + ALPHA), 50 * (3 + 1.5 * N + ALPHA)])
b_mistake = np.array([50 * (3 + 1.5 * N + ALPHA) * (1 + 0.01), 50 * (3 + 1.5 * N + ALPHA) * (1 - 0.01), 50 * (3 + 1.5 * N + ALPHA) * (1 + 0.01)])

In [62]:
print("Матрица СЛАУ\n", A, "\nПравая часть", b, "Правая часть ошибки\n", b_mistake)

Матрица СЛАУ
 [[351.    350.    350.   ]
 [350.7   350.298 350.   ]
 [349.3   350.    351.702]] 
Правая часть [1051. 1051. 1051.] Правая часть ошибки
 [1061.51 1040.49 1061.51]


In [63]:
A_inv = la.inv(A)

In [64]:
print("Обратная матрица к А\n", A_inv)

Обратная матрица к А
 [[ 1.31169874 -1.11544741 -0.1953016 ]
 [-2.03520261  2.23277106 -0.19661235]
 [ 0.72261331 -1.11413666  0.39247196]]


In [65]:
A_abs = np.absolute(A)
A_inv_abs = np.absolute(A_inv)

In [66]:
print("Модуль элементов A\n", A_abs, "\n\n", "Модуль элементов обратной к А\n", A_inv_abs)

Модуль элементов A
 [[351.    350.    350.   ]
 [350.7   350.298 350.   ]
 [349.3   350.    351.702]] 

 Модуль элементов обратной к А
 [[1.31169874 1.11544741 0.1953016 ]
 [2.03520261 2.23277106 0.19661235]
 [0.72261331 1.11413666 0.39247196]]


In [67]:
A_norm = la.norm(A, np.inf)
A_inv_norm = la.norm(A_inv, np.inf) 
cond_A = A_norm * A_inv_norm
check_cond_A = la.cond(A, np.inf)

In [68]:
print("Норма А = ", A_norm, "\nНорма обратной матрицы к А = ", A_inv_norm)
print("Число обусловленности A = ", cond_A, "\nПроверка = ", check_cond_A)

Норма А =  1051.002 
Норма обратной матрицы к А =  4.464586029622445
Число обусловленности A =  4692.288846305249 
Проверка =  4692.288846305249


In [73]:
x = la.solve(A, b)

In [77]:
print("Решение СЛАУ\n", x)

Решение СЛАУ
 [0.99815971 1.00485877 0.99698678]


In [78]:
delta_b = b_mistake - b

In [79]:
print("Дельта b\n", delta_b)

Дельта b
 [ 10.51 -10.51  10.51]


In [80]:
delta_x = np.dot(A_inv, delta_b)

In [81]:
print("Дельта x\n", delta_x)

Дельта x
 [ 23.45668616 -46.92279917  23.42912248]


In [82]:
inac = la.norm(delta_x, np.inf) / la.norm(x, np.inf) 

In [83]:
print("Погрешность\n", inac)

Погрешность
 46.69591461027572


In [84]:
print(cond_A * la.norm(delta_b, np.inf) / la.norm(b, np.inf))

46.92288846305245


In [85]:
##ЗАДАНИЕ 1.2

In [103]:
from numpy.linalg import matrix_power 
import math
import locale

N = 12
n = 52
ALPHA = (60 - n) / 100

In [106]:
a = 0
b = 1
lamb = -ALPHA - 0.6

h = (b-a)/10

s = []
s.append(a + h/2)
for i in range(1, 10):
    s.append(s[i-1] + h)

def myfunc(i, j):
    return math.tanh(s[i]*s[j])*h

print('A')

for i in range(10):
    row = ''
    for j in range(10):
        kek = myfunc(i, j)

        if kek > 0:
            row += locale.str((round(kek, 6))) + ' & '
        else:
            row += locale.str((round(kek, 5))) + ' & '
    row = row[:-2]
    row += '\\\\'
    print(row)
print()
print()
print('E+lambda*A')

matrix = np.zeros((10, 10))
for i in range(10):
    row = ''
    for j in range(10):
        kek = myfunc(i, j)*lamb
        if i==j:
            kek += 1
        matrix[i][j] = kek
        if kek > 0:
            row += locale.str((round(kek, 6))) + ' & '
        else:
            row += locale.str((round(kek, 5))) + ' & '
    row = row[:-2]
    row += '\\\\'
    print(row)

cheb_vector = np.zeros(10)
for i in range(10):
    for j in range(10):
        cheb_vector[i] += abs(matrix[i][j])
print('cheb = ', locale.str((round(max(cheb_vector), 6))))


a = np.zeros(10)
for i in range(10):
    a[i] = 1
vect_b = np.dot(matrix, a)
str = ""
for x in vect_b:
    if x > 0:
        str += locale.str(round(x, 6)) + ' \\\\ '
    else:
        str += locale.str(round(x, 5)) + ' \\\\ '
print("b = ")
print(str)

delta_b = [1, -1, 1 , -1, 1, -1, 1, -1, 1, -1]
for i in range(10):
    delta_b[i] = delta_b[i]*vect_b[i]*0.01

str = ""
for x in delta_b:
    if x > 0:
        str += locale.str(round(x, 6)) + ' \\\\ '
    else:
        str += locale.str(round(x, 5)) + ' \\\\ '
print("delta_b = ")
print(str)

b_full = []
for i in range(10):
    b_full.append(vect_b[i] + delta_b[i])

str = ""
for x in b_full:
    if x > 0:
        str += locale.str(round(x, 6)) + ' \\\\ '
    else:
        str += locale.str(round(x, 5)) + ' \\\\ '
print("full_b = ")
print(str)
matrix_1 = matrix_power(matrix, -1)


print()
print()
print('(E+lambda*A)^-1')
for i in range(10):
    row = ''
    for j in range(10):
        kek = matrix_1[i][j]
        if kek > 0:
            row += locale.str((round(kek, 6))) + ' & '
        else:
            row += locale.str((round(kek, 5))) + ' & '
    row = row[:-2]
    row += '\\\\'
    print(row)


cheb_vector = np.zeros(10)
for i in range(10):
    for j in range(10):
        cheb_vector[i] += abs(matrix_1[i][j])
print('cheb_1 = ', locale.str((round(max(cheb_vector), 6))))


full_x = np.dot(matrix_1, b_full)
str = ""
for x in full_x:
    if x > 0:
        str += locale.str(round(x, 6)) + ' \\\\ '
    else:
        str += locale.str(round(x, 5)) + ' \\\\ '
print("full_x = ")
print(str)

delta_x = []
for i in range(10):
    delta_x.append(full_x[i] - 1)

str = ""
for x in delta_x:
    if x > 0:
        str += locale.str(round(x, 6)) + ' \\\\ '
    else:
        str += locale.str(round(x, 5)) + ' \\\\ '
print("delta_x = ")
print(str)

B = np.zeros((10, 10))
for i in range(10):
    for j in range(10):
        B[i][j] = matrix[i][j]/b_full[i]

print()
print()
print('B')
for i in range(10):
    row = ''
    for j in range(10):
        kek = B[i][j]
        if kek > 0:
            row += locale.str((round(kek, 6))) + ' & '
        else:
            row += locale.str((round(kek, 5))) + ' & '
    row = row[:-2]
    row += '\\\\'
    print(row)

print()
print()
print("B-1")
B_1 = matrix_power(B, -1)
for i in range(10):
    row = ''
    for j in range(10):
        kek = B_1[i][j]
        if kek > 0:
            row += locale.str((round(kek, 6))) + ' & '
        else:
            row += locale.str((round(kek, 5))) + ' & '
    row = row[:-2]
    row += '\\\\'
    print(row)

x_prime = np.dot(B_1, a)
str = ""
for x in x_prime:
    if x > 0:
        str += locale.str(round(x, 6)) + ' \\\\ '
    else:
        str += locale.str(round(x, 5)) + ' \\\\ '
print("x_prime = ")
print(str)

A
0.00025 & 0.00075 & 0.00125 & 0.00175 & 0.00225 & 0.002749 & 0.003249 & 0.003748 & 0.004247 & 0.004746 \\
0.00075 & 0.00225 & 0.003748 & 0.005245 & 0.00674 & 0.008231 & 0.009719 & 0.011203 & 0.012681 & 0.014154 \\
0.00125 & 0.003748 & 0.006242 & 0.008728 & 0.011203 & 0.013664 & 0.016108 & 0.018533 & 0.020936 & 0.023313 \\
0.00175 & 0.005245 & 0.008728 & 0.012189 & 0.015621 & 0.019016 & 0.022365 & 0.025663 & 0.028902 & 0.032077 \\
0.00225 & 0.00674 & 0.011203 & 0.015621 & 0.019978 & 0.024257 & 0.028443 & 0.032524 & 0.036488 & 0.040323 \\
0.002749 & 0.008231 & 0.013664 & 0.019016 & 0.024257 & 0.02936 & 0.034301 & 0.039059 & 0.043618 & 0.047963 \\
0.003249 & 0.009719 & 0.016108 & 0.022365 & 0.028443 & 0.034301 & 0.039903 & 0.045223 & 0.050239 & 0.054938 \\
0.003748 & 0.011203 & 0.018533 & 0.025663 & 0.032524 & 0.039059 & 0.045223 & 0.050983 & 0.056319 & 0.061224 \\
0.004247 & 0.012681 & 0.020936 & 0.028902 & 0.036488 & 0.043618 & 0.050239 & 0.056319 & 0.061846 & 0.066821 \\
0.004746 & 0