In [37]:
import numpy as np
A = np.array([[11, 1, 2, 3],
              [1, 11, 3, 2],
              [2, 3, 11, 1],
              [3, 2, 1, 11]])
A_copy = A.copy()

print(A)
def print_kekw_matrix(A):
    for i in range(4):
            row = ''
            for j in range(4):
                kek = A[i][j]
                row += str(kek).rstrip('0').rstrip('.') + ' & '
            row = row[:-2]
            row += '\\\\'
            print(row)
def print_matrix(matrix):
    if len(matrix.shape) == 2:
        for i in range(matrix.shape[0]):
            row = ''
            for j in range(matrix.shape[1]):
                kek = matrix[i][j]
                if kek > 0:
                    row += str(round(kek, 5)).rstrip('0').rstrip('.') + ' & '
                else:
                    row += str(round(kek, 4)).rstrip('0').rstrip('.') + ' & '
            row = row[:-2]
            row += '\\\\'
            print(row)
    elif len(matrix.shape) == 1:
        row = ''
        for i in range(matrix.shape[0]):
            kek = matrix[i]
            if kek > 0:
                row += str(round(kek, 5)).rstrip('0').rstrip('.') + ' \\\\ '
            else:
                row += str(round(kek, 4)).rstrip('0').rstrip('.') + ' \\\\ '
        print(row)

def get_max_elem(matr):
    D = np.diag(np.diag(matr))
    LU = np.absolute(matr - D)
    amax = np.argmax(LU)
    return amax // LU.shape[1], amax % LU.shape[0]

i = 1

Q_array = []
while True:

    max_elem = get_max_elem(A)
    if abs(A[max_elem]) < 0.01:
        break
    print(f'------------ Iteration {i} ------------')
    print(f'Max element: {max_elem[0] + 1}, {max_elem[1] + 1} = {A[max_elem]}')
    if A[max_elem[0]][max_elem[0]] == A[max_elem[1]][max_elem[1]]:
        print(f'fi = pi/4')
        fi = np.pi / 4
    else:
        # Тут не уверен если кого-то сюда зайдет сами разберетесь))
        fi = np.arctan((A[max_elem[0]][max_elem[0]] - A[max_elem[1]][max_elem[1]])/(2 * A[max_elem[1]][max_elem[0]])) / 2
        print(f'fi = {round(fi, 5)}')

    Q = np.eye(A.shape[0])
    Q[max_elem[0]][max_elem[0]] = np.cos(fi)
    Q[max_elem[0]][max_elem[1]] = -np.sin(fi)
    Q[max_elem[1]][max_elem[0]] = np.sin(fi)
    Q[max_elem[1]][max_elem[1]] = np.cos(fi)
    Q_array.append(Q)
    Q_print = np.eye(A.shape[0]).tolist()

    Q_print[max_elem[0]][max_elem[0]] = "cos \\varphi"
    Q_print[max_elem[0]][max_elem[1]] = "-sin \\varphi"
    Q_print[max_elem[1]][max_elem[0]] = "sin \\varphi"
    Q_print[max_elem[1]][max_elem[1]] = "cos \\varphi"
    print('Q:')
    print_kekw_matrix(Q_print)
    print()
    print_matrix(Q)
    print('Q_t')
    print_matrix(Q.T)
    A = Q.T @ A @ Q
    print('A:')
    print_matrix(A)
    i += 1


[[11  1  2  3]
 [ 1 11  3  2]
 [ 2  3 11  1]
 [ 3  2  1 11]]
------------ Iteration 1 ------------
Max element: 1, 4 = 3
fi = pi/4
Q:
cos \varphi & 0 & 0 & -sin \varphi \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
sin \varphi & 0 & 0 & cos \varphi \\

0.70711 & 0 & 0 & -0.7071 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0.70711 & 0 & 0 & 0.70711 \\
Q_t
0.70711 & 0 & 0 & 0.70711 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
-0.7071 & 0 & 0 & 0.70711 \\
A:
14 & 2.12132 & 2.12132 & -0 \\
2.12132 & 11 & 3 & 0.70711 \\
2.12132 & 3 & 11 & -0.7071 \\
-0 & 0.70711 & -0.7071 & 8 \\
------------ Iteration 2 ------------
Max element: 2, 3 = 3.0
fi = pi/4
Q:
1 & 0 & 0 & 0 \\
0 & cos \varphi & -sin \varphi & 0 \\
0 & sin \varphi & cos \varphi & 0 \\
0 & 0 & 0 & 1 \\

1 & 0 & 0 & 0 \\
0 & 0.70711 & -0.7071 & 0 \\
0 & 0.70711 & 0.70711 & 0 \\
0 & 0 & 0 & 1 \\
Q_t
1 & 0 & 0 & 0 \\
0 & 0.70711 & 0.70711 & 0 \\
0 & -0.7071 & 0.70711 & 0 \\
0 & 0 & 0 & 1 \\
A:
14 & 3 & 0 & -0 \\
3 & 14 & -0 & 0 \\
0 & -0 & 8 & -1 \\
-0 & 0 & -1

In [38]:
import functools
print(f'Q[{i-2}]')
Q = functools.reduce(lambda a, b : a @ b, Q_array)
print_matrix(Q)

Q[3]
0.5 & -0.5 & -0.5 & -0.5 \\
0.5 & 0.5 & -0.5 & 0.5 \\
0.5 & 0.5 & 0.5 & -0.5 \\
0.5 & -0.5 & 0.5 & 0.5 \\


In [44]:
A = A_copy
print('Aq1 = ')
print_matrix(A@(Q[:, 0]))
print('Aq2 = ')
print_matrix(A@(Q[:, 1]))
print('Aq3 = ')
print_matrix(A@(Q[:, 2]))
print('Aq4 = ')
print_matrix(A@(Q[:, 3]))

Aq1 = 
[8.5 8.5 8.5 8.5]
8.5 \\ 8.5 \\ 8.5 \\ 8.5 \\ 
Aq2 = 
-5.5 \\ 5.5 \\ 5.5 \\ -5.5 \\ 
Aq3 = 
-3.5 \\ -3.5 \\ 3.5 \\ 3.5 \\ 
Aq4 = 
-4.5 \\ 4.5 \\ -4.5 \\ 4.5 \\ 
